add_newline=false

format = """
$cmd_duration$git_branch $git_commit
$directory$character"""

[character]
success_symbol = "[â¯](bold green)"
vicmd_symbol = "[V](bold blue)"
error_symbol = "[X](bold red)"

